# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ganaste.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(505, 159)

        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 521, 161))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        #Generamos el boton Que abrira la ventana principal
        self.Nuevo_Juego = QtWidgets.QPushButton(self.frame)
        self.Nuevo_Juego.setGeometry(QtCore.QRect(300, 90, 141, 31))
        self.Nuevo_Juego.setObjectName("Nuevo_Juego")
        #Label que mostrara si gano o persio el usuario
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(100, 10, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        #Boton donde podremos salirnos
        self.Salir = QtWidgets.QPushButton(self.frame)
        self.Salir.setGeometry(QtCore.QRect(90, 90, 88, 27))
        self.Salir.setObjectName("Salir")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Nuevo_Juego.setText(_translate("Form", "Jugar de Nuevo"))
        self.Salir.setText(_translate("Form", "Salir"))
